config/routes.rb
Rails.application.routes.draw do

  # 会員機能(ユーザー側)
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_user_session'
  end

  # トップページ
  root to: 'public/homes#top'

  # 利用者側
  scope module: :public do
    # ユーザー実装
    resources :users, only: [:index, :show, :edit, :update]
    # ゲーム機能
    resources :games, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      # コメント機能
      resources :comments, only: [:create, :destroy]
      # お気に入り機能
      resource :favorites, only: [:create, :destroy]
    end
  end

  # ユーザー退会機能
  get 'users/:id/unsubscribe'=>'public/users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/withdraw'=>'public/users#withdraw', as: 'user_withdraw'

  # ゲーム検索ページ(画像入手)
  get 'search'=>'public/games#search', as: 'game_search'



  # 会員機能(管理者側)
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

    # 管理者トップ画面
    get '/admin'=>'admin/homes#top', as: 'admin_home'

    namespace :admin do
      # ユーザー機能
      resources :users, only: [:show]
      # ゲーム機能
      resources :games, only: [:index, :show, :destroy] do
        # コメント機能
        resources :comments, only: [:destroy]
      end
      # コメント機能(一覧画面)
      resources :comments, only: [:index]
      # ジャンル機能
      resources :genres, only: [:new, :edit, :create, :update, :destroy]
    end

    # 管理者ユーザー停止機能
    patch 'admin/users/:id/withdraw'=>'admin/users#withdraw', as: 'admin_user_withdraw'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord

  # アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :genre

  # バリデーション
  validates :title, presence: { message: 'を入力してください' }
  validates :play_condition, presence: { message: 'を入力してください' }

  # お気に入り機能
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  # ゲーム画像実装
  has_one_attached :image

  # プレイ状況をenumで実装
  enum play_condition: { not_play: 0, play_soon: 1, have_played: 2 }
end

app/controllers/admin/games_controller.rb
# 管理者用コントローラー
class Admin::GamesController < ApplicationController
  def index
    @games = Game.page(params[:page])
  end

  def show
    @game = Game.find(params[:id])
    @user = @game.user
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to admin_games_path(game)
  end
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/views/admin/games/index.html.erb
<!--管理者ページ-->
<div class="container">

  <!--ページタイトル-->
  <div class="row mt-4 pl-3">
    <h4>ゲーム投稿一覧</h4>
  </div>

  <!--ゲーム投稿一覧-->
  <div class="row mt-3 d-flex justify-content-center">
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th>ゲーム画像</th>
          <th>タイトル</th>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <!--ゲーム画像が送られていればそれを表示、送られていなければno_image画像を表示-->
            <td>
              <% if game.smallImageUrl.present? %>
                <%= image_tag game.smallImageUrl %>
              <% else %>
                <%= image_tag asset_path('no_image.jpg'), size: "100×100" %>
              <% end %>
            </td>
            <td><%= game.title %></td>
            <td><%= game.genre.name %></td>
            <td><%= link_to "詳細", admin_game_path(game.id), class:"btn btn-success" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <!--ページネーション-->
    <%= paginate @games %>
  </div>
</div>

app/views/admin/games/show.html.erb
<!--管理者ページ-->

<!--フラッシュメッセージ-->
<div id="notice"><%= flash[:notice] %></div>

<div class="container">
  <!--ページタイトル-->
  <div class="row mt-4 pl-3">
    <div class="col-md-3">
      <h4>ゲーム詳細</h4>
    </div>
    <div class="col-md-7">
    </div>
    <div class="col-md-2">
      <%= link_to "削除する", admin_game_path, method: :delete, "data-confirm" => "投稿を削除しますか？", class:"btn btn-danger" %>
    </div>
  </div>


  <!--投稿ゲーム画像-->
  <div class="row mt-2 d-flex justify-content-center">
    <% if @game.largeImageUrl.present? %>
      <%= image_tag @game.largeImageUrl %>
    <% else %>
      <%= image_tag asset_path('no_image.jpg'), size: "200×200" %>
    <% end %>
  </div>

  <div class="row mt-4 d-flex justify-content-center">
    <label class="col-md-2 col-form-label">投稿日</label>
    <div class="col-md-4 col-form-label">
      <%= @game.created_at.strftime('%Y/%m/%d %R:%S') %>
    </div>
  </div>

  <!--投稿主-->
  <div class="row mt-2 d-flex justify-content-center">
    <label class="col-md-2 col-form-label">投稿主</label>
    <div class="col-md-4 col-form-label">
      <%= link_to admin_user_path(@user) do %>
        <%= @user.nickname %>
      <% end %>
    </div>
  </div>

  <!--タイトル-->
  <div class="row mt-2 d-flex justify-content-center">
    <label class="col-md-2 col-form-label">ゲームタイトル</label>
    <div class="col-md-4 col-form-label">
      <%= @game.title %>
    </div>
  </div>

  <!--プレイ状況-->
  <div class="row mt-2 d-flex justify-content-center">
    <label class="col-md-2 col-form-label">プレイ状況</label>
    <div class="col-md-4 col-form-label">
      <%= I18n.t("enums.game.play_condition." + @game.play_condition) %>
    </div>
  </div>

  <!--ジャンル-->
  <div class="row mt-2 d-flex justify-content-center">
    <label class="col-md-2 col-form-label">ジャンル</label>
    <div class="col-md-4 col-form-label">
      <%= @game.genre.name %>
    </div>
  </div>

  <!--つぶやき-->
  <div class="row mt-2 d-flex justify-content-center">
    <label class="col-md-2 col-form-label">つぶやき</label>
    <div class="col-md-4 col-form-label">
      <%= @game.opinion %>
    </div>
  </div>

  <!--コメント-->
  <div class="row mt-3 pl-3">
    <div class="comment">
      <h4>コメント</h4>
    </div>
  </div>

  <!--コメント数-->
  <div class="row mt-3">
    <p><%= @game.comments.count %> コメント</p>
  </div>

  <!--コメント-->
  <div class="row mt-2 d-flex justify-content-center">
    <table class="table">
      <thead>
        <tr>
          <th>投稿日</th>
          <th>投稿者</th>
          <th>コメント</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @game.comments.each do |comment| %>
          <tr>
            <th>
              <%= comment.created_at.strftime('%Y/%m/%d') %><br>
              <%= comment.created_at.strftime('%R:%S') %>
            </th>
            <th>
              <% if comment.user.is_deleted == false %>
                <%= link_to admin_user_path(comment.user_id) do %>
                  <%= image_tag comment.user.get_profile_image(100, 100) %><br>
                  <%= comment.user.nickname %>
                <% end %>
              <% else %>
                <%= link_to "このユーザーは退会しています", admin_user_path(comment.user_id) %>
              <% end %>
            </th>
            <th><%= comment.comment %></th>
            <th>
              <%= link_to "削除する", admin_game_comment_path(comment.game, comment), method: :delete, "data-confirm" => "コメントを削除しますか？", class:"btn btn-danger" %>
            </th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>