config/routes.rb
Rails.application.routes.draw do

  # 会員機能(ユーザー側)
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_user_session'
  end

  # トップページ
  root to: 'public/homes#top'

  # 利用者側
  scope module: :public do
    # ユーザー実装
    resources :users, only: [:index, :show, :edit, :update]
    # ゲーム機能
    resources :games, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      # コメント機能
      resources :comments, only: [:create, :destroy]
      # お気に入り機能
      resource :favorites, only: [:create, :destroy]
    end
  end

  # ユーザー退会機能
  get 'users/:id/unsubscribe'=>'public/users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/withdraw'=>'public/users#withdraw', as: 'user_withdraw'

  # ゲーム検索ページ(画像入手)
  get 'search'=>'public/games#search', as: 'game_search'



  # 会員機能(管理者側)
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

    # 管理者トップ画面
    get '/admin'=>'admin/homes#top', as: 'admin_home'

    namespace :admin do
      # ユーザー機能
      resources :users, only: [:show]
      # ゲーム機能
      resources :games, only: [:index, :show, :destroy] do
        # コメント機能
        resources :comments, only: [:destroy]
      end
      # コメント機能(一覧画面)
      resources :comments, only: [:index]
      # ジャンル機能
      resources :genres, only: [:new, :edit, :create, :update, :destroy]
    end

    # 管理者ユーザー停止機能
    patch 'admin/users/:id/withdraw'=>'admin/users#withdraw', as: 'admin_user_withdraw'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord

  # アソシエーション
  has_many :games, dependent: :destroy

  validates :name, presence: { message: 'を入力してください' }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to new_admin_genre_path(genre.id)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to new_admin_genre_path
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to new_admin_genre_path(genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<!--管理者ページ-->
<div class="container">
  <div class="row mt-4 pl-3">
    <h4>ジャンル編集</h4>
  </div>

  <!--ジャンル編集入力欄-->
  <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <!--ジャンルタイトル-->
    <div class="row mt-4 d-flex justify-content-center">
      <label for="name" class="col-md-2 col-form-label">ジャンル名</label>
      <div class="col-md-5">
        <%= f.text_field :name, class:"form-control", id:"name" %>
      </div>
    </div>

    <div class="row mt-3 d-flex justify-content-center">
      <%= f.submit "編集", class:"btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admin/genres/new.html.erb
<!--管理者ページ-->
<div class="container">
  <!--ページタイトル-->
  <div class="row mt-4 pl-3">
    <h4>ジャンル登録/一覧</h4>
  </div>

  <!--ジャンル登録-->
    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
      <!--ジャンル名入力欄-->
      <div class="row mt-4">
        <label for="name" class="col-md-2 col-form label">ジャンル名</label>
        <div class="col-md-5">
          <%= f.text_field :name, class:"form-control", id:"name" %>
        </div>
      </div>

      <!--登録ボタン-->
      <div class="row mt-3">
        <%= f.submit "登録", class:"btn btn-success" %>
      </div>
    <% end %>

    <div class="row mt-4 pl-3">
      <h4>ジャンル一覧</h4>
    </div>

    <!--ジャンル一覧-->
    <div class="row mt-4">
      <table class="table">
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <th><%= genre.name %></th>
              <th><%= link_to "編集", edit_admin_genre_path(genre.id), class:"btn btn-primary" %></th>
              <th><%= link_to "削除", admin_genre_path(genre.id), method: :delete, "data-confirm" => "削除しますか？", class:"btn btn-danger" %></th>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
</div>