config/routes.rb
Rails.application.routes.draw do

  # 会員機能(ユーザー側)
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_user_session'
  end

  # トップページ
  root to: 'public/homes#top'

  # 利用者側
  scope module: :public do
    # ユーザー実装
    resources :users, only: [:index, :show, :edit, :update]
    # ゲーム機能
    resources :games, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      # コメント機能
      resources :comments, only: [:create, :destroy]
      # お気に入り機能
      resource :favorites, only: [:create, :destroy]
    end
  end

  # ユーザー退会機能
  get 'users/:id/unsubscribe'=>'public/users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/withdraw'=>'public/users#withdraw', as: 'user_withdraw'

  # ゲーム検索ページ(画像入手)
  get 'search'=>'public/games#search', as: 'game_search'



  # 会員機能(管理者側)
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

    # 管理者トップ画面
    get '/admin'=>'admin/homes#top', as: 'admin_home'

    namespace :admin do
      # ユーザー機能
      resources :users, only: [:show]
      # ゲーム機能
      resources :games, only: [:index, :show, :destroy] do
        # コメント機能
        resources :comments, only: [:destroy]
      end
      # コメント機能(一覧画面)
      resources :comments, only: [:index]
      # ジャンル機能
      resources :genres, only: [:new, :edit, :create, :update, :destroy]
    end

    # 管理者ユーザー停止機能
    patch 'admin/users/:id/withdraw'=>'admin/users#withdraw', as: 'admin_user_withdraw'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
# 管理者用コントローラー
class Admin::HomesController < ApplicationController
  def top
    @users = User.page(params[:page])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<!--管理者ページ-->
<div id="notice"><%= flash[:notice] %></div>
<div class="container">
  <div class="row mt-4 pl-3">
    <h4>ユーザ一覧</h4>
  </div>

  <div class="row mt-3 d-flex justify-content-center">
    <table class="table">
      <thead>
        <tr>
          <th>会員ID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th>退会ステータス</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.nickname %></td>
            <td><%= user.email %></td>
            <td>
              <% if user.is_deleted == true %>
                <p class="text-secondary">退会済み</p>
              <% else %>
                <p class="text-success">有効</p>
              <% end %>
            </td>
            <td><%= link_to "詳細", admin_user_path(user.id), class:"btn btn-success" %></td>
            <td>
              <% if user.is_deleted == false %>
                <%= link_to "停止", admin_user_withdraw_path(user.id), method: :patch, "data-confirm" => "このユーザーを利用停止しますか?", class:"btn btn-secondary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <!--ページネーション-->
    <%= paginate @users %>
  </div>
</div>