config/routes.rb
Rails.application.routes.draw do

  # 会員機能(ユーザー側)
  devise_for :users, controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
    passwords: 'public/passwords'
  }

  # ゲストログイン
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'guest_user_session'
  end

  # トップページ
  root to: 'public/homes#top'

  # 利用者側
  scope module: :public do
    # ユーザー実装
    resources :users, only: [:index, :show, :edit, :update]
    # ゲーム機能
    resources :games, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      # コメント機能
      resources :comments, only: [:create, :destroy]
      # お気に入り機能
      resource :favorites, only: [:create, :destroy]
    end
  end

  # ユーザー退会機能
  get 'users/:id/unsubscribe'=>'public/users#unsubscribe', as: 'user_unsubscribe'
  patch 'users/:id/withdraw'=>'public/users#withdraw', as: 'user_withdraw'

  # ゲーム検索ページ(画像入手)
  get 'search'=>'public/games#search', as: 'game_search'



  # 会員機能(管理者側)
  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

    # 管理者トップ画面
    get '/admin'=>'admin/homes#top', as: 'admin_home'

    namespace :admin do
      # ユーザー機能
      resources :users, only: [:show]
      # ゲーム機能
      resources :games, only: [:index, :show, :destroy] do
        # コメント機能
        resources :comments, only: [:destroy]
      end
      # コメント機能(一覧画面)
      resources :comments, only: [:index]
      # ジャンル機能
      resources :genres, only: [:new, :edit, :create, :update, :destroy]
    end

    # 管理者ユーザー停止機能
    patch 'admin/users/:id/withdraw'=>'admin/users#withdraw', as: 'admin_user_withdraw'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  # アソシエーション
  belongs_to :user
  belongs_to :game
  
  #バリデーション
  validates :comment, presence: { message: 'を入力してください' }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  # バリデーション
  validates :user_id, uniqueness: { scope: :game_id }

  # アソシエーション
  belongs_to :user
  belongs_to :game


end

app/models/game.rb
class Game < ApplicationRecord

  # アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :genre

  # バリデーション
  validates :title, presence: { message: 'を入力してください' }
  validates :play_condition, presence: { message: 'を入力してください' }

  # お気に入り機能
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

  # ゲーム画像実装
  has_one_attached :image

  # プレイ状況をenumで実装
  enum play_condition: { not_play: 0, play_soon: 1, have_played: 2 }
end

app/models/genre.rb
class Genre < ApplicationRecord

  # アソシエーション
  has_many :games, dependent: :destroy

  validates :name, presence: { message: 'を入力してください' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ゲストユーザー
  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "GuestUser"
    end
  end

  # バリデーション
  validates :nickname, presence: { message: 'を入力してください' }

  # アソシエーション
  has_many :games, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 画像の実装
  has_one_attached :profile_image

  # プロフィール画像の実装
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/comments_controller.rb
# 管理者用コントローラー
class Admin::CommentsController < ApplicationController

  def index
    @comments = Comment.page(params[:page])
  end

  def destroy
    comment = Comment.find(params[:id])
    if comment.destroy
      flash[:notice] = "コメントを削除しました"
      redirect_to admin_game_path(params[:game_id])
    end
  end
end

app/controllers/admin/games_controller.rb
# 管理者用コントローラー
class Admin::GamesController < ApplicationController
  def index
    @games = Game.page(params[:page])
  end

  def show
    @game = Game.find(params[:id])
    @user = @game.user
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to admin_games_path(game)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def new
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    genre = Genre.new(genre_params)
    genre.save
    redirect_to new_admin_genre_path(genre.id)
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to new_admin_genre_path
  end

  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to new_admin_genre_path(genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
# 管理者用コントローラー
class Admin::HomesController < ApplicationController
  def top
    @users = User.page(params[:page])
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
# 管理者ページ
class Admin::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @games = @user.games.page(params[:page])
    @favorites = Favorite.where(user_id: @user)
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    redirect_to admin_home_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # bootstrapのフラッシュを定義
  add_flash_types :success, :danger
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!--ヘッダー、フッター画面-->
<!DOCTYPE html>
<html>
  <head>
    <title>GameCircle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--ヘッダー-->
  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm" style="background-color: #87cefa;">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand" href="/"><%= image_tag 'gamelogo.png' %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user), class:"nav-link text-white" do %>
                    <i class="fas fa-user"></i> マイページ
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to game_search_path, class:"nav-link text-white" do %>
                    <i class="fas fa-search"></i> 探す
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to games_path, class:"nav-link text-white" do %>
                    <i class="fas fa-gamepad"></i> 投稿一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class:"nav-link text-white" do %>
                    <i class="fas fa-users"></i> ユーザー
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-white" do %>
                    <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </li>
              <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to new_admin_genre_path, class:"nav-link text-white" do %>
                  <i class="fas fa-plus"></i> ジャンル登録/一覧
                <% end %>
              </li>
                <li class="nav-item">
                  <%= link_to admin_home_path, class:"nav-link text-white" do %>
                    <i class="fas fa-users"></i> ユーザ一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_games_path, class:"nav-link text-white" do %>
                    <i class="fas fa-gamepad"></i> ゲーム一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to admin_comments_path, class:"nav-link text-white" do %>
                  <i class="fas fa-comments"></i> コメント一覧
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_admin_session_path, method: :delete, class:'nav-link text-white' do %>
                    <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class:"nav-link text-white" do %>
                    <i class="fas fa-user-plus"></i> 新規登録
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class:"nav-link text-white" do %>
                    <i class="fas fa-sign-in-alt"></i> ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>

    <!--フッター-->
    <footer class="shadow-sm pt-5 pb-4" style="background-color: #87cefa;">
      <div class="container">
        <div class="row d-flex justify-content-center">
          <a href="https://webservice.rakuten.co.jp/" target="_blank"><img src="https://webservice.rakuten.co.jp/img/credit/200709/credit_31130.gif" border="0" alt="Rakuten Web Service Center" title="Rakuten Web Service Center" width="311" height="30"/></a>
        </div>
      </div>
    </footer>
  </body>
</html>